export const NIGERIA_STATES: string[] = [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
    'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT',
    'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi',
    'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo',
    'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
];

export const STATE_CITIES: Record<string, string[]> = {
    'Abia': ['Umuahia', 'Aba', 'Ohafia', 'Arochukwu'],
    'Adamawa': ['Yola', 'Mubi', 'Jimeta', 'Numan', 'Gombi'],
    'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak'],
    'Anambra': ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Agulu'],
    'Bauchi': ['Bauchi', 'Azare', 'Misau', 'Katagum', 'Ningi'],
    'Bayelsa': ['Yenagoa', 'Ogbia', 'Sagbama', 'Brass', 'Nembe'],
    'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Vandeikya', 'Adikpo'],
    'Borno': ['Maiduguri', 'Bama', 'Biu', 'Dikwa', 'Jere'],
    'Cross River': ['Calabar', 'Ugep', 'Ikom', 'Ogoja', 'Obudu'],
    'Delta': ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor', 'Effurun'],
    'Ebonyi': ['Abakaliki', 'Afikpo', 'Onueke', 'Ezzamgbo', 'Ishielu'],
    'Edo': ['Benin City', 'Ekpoma', 'Uromi', 'Auchi', 'Ubiaja'],
    'Ekiti': ['Ado-Ekiti', 'Ikere-Ekiti', 'Ilawe-Ekiti', 'Efon-Alaaye', 'Ijero-Ekiti'],
    'Enugu': ['Enugu', 'Nsukka', 'Nkpor', 'Oji River', 'Agbani'],
    'FCT': ['Abuja', 'Gwagwalada', 'Kuje', 'Karshi', 'Bwari'],
    'Gombe': ['Gombe', 'Kumo', 'Billiri', 'Dukku', 'Nafada'],
    'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Oguta', 'Mbaise'],
    'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Birnin Kudu', 'Ringim'],
    'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Saminaka', 'Birnin Gwari'],
    'Kano': ['Kano', 'Kumbotso', 'Dawakin Tofa', 'Tudun Wada', 'Rano'],
    'Katsina': ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Dutsin-Ma'],
    'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega'],
    'Kogi': ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Ankpa'],
    'Kwara': ['Ilorin', 'Offa', 'Ilesha Baruba', 'Omu-Aran', 'Lafiagi'],
    'Lagos': ['Ikeja', 'Lagos', 'Lekki', 'Badagry', 'Epe', 'Ikorodu'],
    'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa', 'Doma'],
    'Niger': ['Minna', 'Bida', 'Kontagora', 'Suleja', 'Lapai'],
    'Ogun': ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ilaro', 'Ota'],
    'Ondo': ['Akure', 'Ondo', 'Owo', 'Ore', 'Ikare'],
    'Osun': ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo'],
    'Oyo': ['Ibadan', 'Oyo', 'Ogbomoso', 'Iseyin', 'Saki'],
    'Plateau': ['Jos', 'Bukuru', 'Pankshin', 'Shendam', 'Mangu'],
    'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Okrika', 'Omoku', 'Ahoada'],
    'Sokoto': ['Sokoto', 'Gwadabawa', 'Wurno', 'Tambuwal', 'Isa'],
    'Taraba': ['Jalingo', 'Wukari', 'Bali', 'Serti', 'Mutum-Biyu'],
    'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Geidam'],
    'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Bungudu'],
};

export const STATE_LGAS: Record<string, string[]> = {
    'Abia': ['Umuahia North', 'Umuahia South', 'Osisoma', 'Aba North', 'Aba South', 'Ohafia', 'Arochukwu'],
    'Adamawa': ['Yola North', 'Yola South', 'Girei', 'Mubi North', 'Mubi South', 'Numan', 'Gombi'],
    'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak', 'Etim Ekpo'],
    'Anambra': ['Awka North', 'Awka South', 'Onitsha North', 'Onitsha South', 'Nnewi North', 'Nnewi South', 'Anambra East', 'Anambra West'],
    'Bauchi': ['Bauchi', 'Azare', 'Misau', 'Katagum', 'Ningi', 'Tafawa Balewa'],
    'Bayelsa': ['Yenagoa', 'Ogbia', 'Sagbama', 'Brass', 'Nembe', 'Southern Ijaw'],
    'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Vandeikya', 'Adikpo', 'Guma'],
    'Borno': ['Maiduguri', 'Bama', 'Biu', 'Dikwa', 'Jere', 'Konduga'],
    'Cross River': ['Calabar South', 'Calabar Municipality', 'Ikom', 'Ogoja', 'Obudu', 'Ugep'],
    'Delta': ['Oshimili North', 'Oshimili South', 'Warri North', 'Warri South', 'Warri South West', 'Sapele', 'Ughelli North', 'Ughelli South', 'Ika North East', 'Ika South'],
    'Ebonyi': ['Abakaliki', 'Afikpo North', 'Afikpo South', 'Ezza North', 'Ezza South', 'Ishielu'],
    'Edo': ['Oredo', 'Egor', 'Ikpoba-Okha', 'Esan West', 'Esan Central', 'Etsako West', 'Etsako Central', 'Etsako East'],
    'Ekiti': ['Ado-Ekiti', 'Ikere', 'Ilawe-Ekiti', 'Efon', 'Ijero', 'Ekiti South West', 'Ekiti West'],
    'Enugu': ['Enugu East', 'Enugu North', 'Enugu South', 'Nsukka', 'Oji River', 'Nkanu East', 'Nkanu West'],
    'FCT': ['Abaji', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali', 'Municipal Area Council'],
    'Gombe': ['Gombe', 'Kumo', 'Billiri', 'Dukku', 'Nafada', 'Akko'],
    'Imo': ['Owerri Municipal', 'Owerri North', 'Owerri West', 'Orlu', 'Okigwe', 'Oguta', 'Mbaitoli'],
    'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Birnin Kudu', 'Ringim', 'Kiyawa'],
    'Kaduna': ['Kaduna North', 'Kaduna South', 'Chikun', 'Zaria', 'Sabon Gari', 'Kafanchan', 'Birnin Gwari'],
    'Kano': ['Kano Municipal', 'Fagge', 'Dala', 'Kumbotso', 'Nassarawa', 'Tarauni', 'Gwale', 'Ungogo'],
    'Katsina': ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Dutsin-Ma', 'Batagarawa'],
    'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega', 'Kalgo'],
    'Kogi': ['Lokoja', 'Okene', 'Kabba/Bunu', 'Idah', 'Ankpa', 'Adavi'],
    'Kwara': ['Ilorin East', 'Ilorin South', 'Ilorin West', 'Offa', 'Oyun', 'Moro'],
    'Lagos': ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ifako-Ijaiye', 'Ikeja', 'Ikorodu', 'Kosofe', 'Lagos Island', 'Lagos Mainland', 'Mushin', 'Ojo', 'Oshodi-Isolo', 'Somolu', 'Surulere'],
    'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa', 'Doma', 'Karu'],
    'Niger': ['Bosso', 'Chanchaga', 'Bida', 'Kontagora', 'Suleja', 'Lapai', 'Mokwa'],
    'Ogun': ['Abeokuta North', 'Abeokuta South', 'Ijebu North', 'Ijebu Ode', 'Sagamu', 'Yewa North', 'Yewa South', 'Ado-Odo/Ota'],
    'Ondo': ['Akure North', 'Akure South', 'Ondo East', 'Ondo West', 'Owo', 'Ore', 'Ikare'],
    'Osun': ['Osogbo', 'Ife Central', 'Ife East', 'Ife North', 'Ife South', 'Ilesa East', 'Ilesa West', 'Ede North', 'Ede South', 'Iwo'],
    'Oyo': ['Ibadan North', 'Ibadan North East', 'Ibadan North West', 'Ibadan South East', 'Ibadan South West', 'Akinyele', 'Oyo East', 'Oyo West', 'Ogbomoso North', 'Ogbomoso South', 'Iseyin', 'Saki East', 'Saki West'],
    'Plateau': ['Jos North', 'Jos South', 'Jos East', 'Pankshin', 'Shendam', 'Mangu', 'Barkin Ladi'],
    'Rivers': ['Port Harcourt', 'Obio/Akpor', 'Bonny', 'Okrika', 'Ogba/Egbema/Ndoni', 'Ahoada East', 'Ahoada West', 'Eleme'],
    'Sokoto': ['Sokoto North', 'Sokoto South', 'Gwadabawa', 'Wurno', 'Tambuwal', 'Isa', 'Dange Shuni'],
    'Taraba': ['Jalingo', 'Wukari', 'Bali', 'Serti', 'Mutum-Biyu', 'Ardo-Kola'],
    'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Geidam', 'Bade'],
    'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Bungudu', 'Maradun'],
};

export const getCitiesForState = (state: string): string[] => STATE_CITIES[state] ?? [];
export const getLgasForState = (state: string): string[] => STATE_LGAS[state] ?? [];
