'use client';
import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import OnboardingLayout from '@/components/OnboardingLayout/OnboardingLayout';
import ProgressBar from '@/components/Onboarding/ProgressBar';
import OptionCard from '@/components/Onboarding/OptionCard';
import { useOnboarding } from '@/contexts/OnboardingContext';

const FILING_TYPES: Record<string, 'Individual' | 'Business'> = {
    'Individual / Freelancer': 'Individual',
    'Joint Filing (Spousal)': 'Individual',
    'Corporate Entity (LLC/Ltd)': 'Business',
    'Registered Enterprise': 'Business',
    'Tax Practitioner / Accountant': 'Business',
    'Trust or Estate': 'Business',
};

export default function Step1() {
    const { data, setFilingType } = useOnboarding();
    const [selections, setSelections] = useState<string[]>(
        data.filingType ? [data.filingType] : []
    );

    const toggleSelection = (option: string) => {
        setSelections([option]);
        setFilingType(option);
    };

    const options = [
        {
            label: 'Individual / Freelancer',
            description: 'Personal Income Tax (PIT) for employees, sole traders, or gig workers.'
        },
        {
            label: 'Joint Filing (Spousal)',
            description: 'Combined filing for married couples seeking to optimize consolidated reliefs and allowances.'
        },
        {
            label: 'Corporate Entity (LLC/Ltd)',
            description: 'For companies subject to Companies Income Tax (CIT) and education tax.'
        },
        {
            label: 'Registered Enterprise',
            description: 'For small-scale businesses and shops filing under the presumptive tax regime.'
        },
        {
            label: 'Tax Practitioner / Accountant',
            description: 'Professional mode for filing on behalf of third-party clients or managed firms.'
        },
        {
            label: 'Trust or Estate',
            description: 'For the management of assets and income generated by a deceased person\'s estate.'
        }
    ];

    const isValid = selections.length > 0;

    return (
        <OnboardingLayout>
            <div className="max-w-xl mx-auto w-full">
                <h2 className="text-lg font-medium text-taxable-dark mb-2">Let's personalize Taxable for you</h2>
                <ProgressBar currentStep={1} />

                <h3 className="text-base font-medium text-taxable-dark mb-4">Who are you filing taxes for?</h3>

                <div className="flex flex-col gap-1 mb-8">
                    {options.map((option) => (
                        <OptionCard
                            key={option.label}
                            label={option.label}
                            description={option.description}
                            isSelected={selections.includes(option.label)}
                            onChange={() => toggleSelection(option.label)}
                        />
                    ))}
                </div>

                <Link 
                    href="/onboarding/step2" 
                    className={`flex items-center justify-center w-full h-11 font-medium rounded-lg shadow-lg transition-transform active:scale-[0.99] ${
                        isValid 
                            ? 'bg-taxable-blue hover:opacity-90 text-white shadow-taxable-blue/10' 
                            : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                    }`}
                    onClick={(e) => !isValid && e.preventDefault()}
                >
                    Next
                </Link>
            </div>
        </OnboardingLayout>
    );
}