'use client';
import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import OnboardingLayout from '@/components/OnboardingLayout/OnboardingLayout';
import ProgressBar from '@/components/Onboarding/ProgressBar';
import OptionCard from '@/components/Onboarding/OptionCard';
import { useOnboarding } from '@/contexts/OnboardingContext';

export default function Step1() {
    const router = useRouter();
    const { data, setFilingType } = useOnboarding();
    const [selections, setSelections] = useState<string[]>(
        data.filingType ? [data.filingType] : []
    );

    const toggleSelection = (option: string) => {
        setSelections([option]);
        setFilingType(option);
    };

    const options = [
        {
            label: 'Individual / Freelancer',
            description: 'Personal Income Tax (PIT) for employees, sole traders, or gig workers.'
        },
        {
            label: 'Joint Filing (Spousal)',
            description: 'Combined filing for married couples seeking to optimize consolidated reliefs and allowances.'
        },
        {
            label: 'Corporate Entity (LLC/Ltd)',
            description: 'For companies subject to Companies Income Tax (CIT) and education tax.'
        },
        {
            label: 'Registered Enterprise',
            description: 'For small-scale businesses and shops filing under the presumptive tax regime.'
        },
        {
            label: 'Tax Practitioner / Accountant',
            description: 'Professional mode for filing on behalf of third-party clients or managed firms.'
        },
        {
            label: 'Trust or Estate',
            description: 'For the management of assets and income generated by a deceased person\'s estate.'
        }
    ];

    const isValid = selections.length > 0;

    return (
        <OnboardingLayout>
            <div className="max-w-xl mx-auto w-full">
                <h2 className="text-7 font-medium text-taxable-dark mb-2">Let's personalize Taxable for you</h2>
                <ProgressBar currentStep={1} />

                <h3 className="text-5 font-medium text-taxable-dark mb-4">Who are you filing taxes for?</h3>

                <div className="flex flex-col gap-1 mb-8">
                    {options.map((option) => (
                        <OptionCard
                            key={option.label}
                            label={option.label}
                            description={option.description}
                            isSelected={selections.includes(option.label)}
                            onChange={() => toggleSelection(option.label)}
                        />
                    ))}
                </div>

                <button
                    onClick={() => isValid && router.push('/onboarding/step2')}
                    disabled={!isValid}
                    className="w-full h-12 bg-taxable-blue text-white font-semibold rounded-xl disabled:bg-neutral-100 disabled:text-neutral-400"
                >
                    Next
                </button>
            </div>
        </OnboardingLayout>
    );
}